tiny object Control 230818 에러
180 line followCube.dis_measure()
Traceback (most recent call last):
File "<string>", line 180, in loop
TypeError: dis_measure() missing 1 required positional argument: 'self'
참고 링크 https://wikidocs.net/8033
인스턴스를 보내줘야 self로 받는데 인스턴스가 없어 에러가 났던 것. 어제 발생한 에러와 관련이 있음.
인스턴스 포함으로 수정